### PR TITLE
chore(deps): update app-runtime to latest

### PR DESCRIPTION
**Pull request by ismay**
https://jira.dhis2.org/browse/LIBS-200. Updating to the new app-runtime release.

### CODE REVIEW

**Comment by Mohammer5** [comment]
For some reasons this app does not have the `@dhis2/prop-types` dependency, I'll try to create a PR because I can't start the app

**Review by varl — APPROVED** [review]
Tested OK against 2.36.

**Comment by ismay** [comment]
I'll hold off on merging this as @Mohammer5 wanted to take a look at the CI tests before we merge this.

**Comment by Mohammer5** [comment]
This is going to end up in 2.38, right? Then I guess you can simply merge it, I can make the tests work again before 2.38 will be release :wink:

**Comment by ismay** [comment]
> This is going to end up in 2.38, right? Then I guess you can simply merge it, I can make the tests work again before 2.38 will be release 😉

Yeah true. Ok cool, I'll do that 👍

**Pull request merged**
